(() => {
  const messages = {
    title: ['冒险档案', 'ADVENTURER'], hud: ['X Focus 每日任务', 'X Focus daily quests'], settings: ['任务设置', 'Quest settings'], collapse: ['收起任务卡', 'Collapse quest card'], expand: ['展开 X Focus 每日任务', 'Expand X Focus daily quests'],
    adventurer: ['冒险者', 'Adventurer'], identityHint: ['登录 X 后自动识别账号', 'Your account is detected after signing in to X'], verified: ['X 蓝 V 已认证', 'X blue verified'], readAt: ['{date} 读取', 'Read {date}'],
    rank0: ['启程旅人', 'Wayfarer'], rank1: ['暮光游侠', 'Dusk Ranger'], rank2: ['星辉行者', 'Starstrider'], rank3: ['黎明守望', 'Dawn Warden'],
    rankHint: ['等级称号：Lv.1 启程旅人 · Lv.5 暮光游侠 · Lv.15 星辉行者 · Lv.30 黎明守望', 'Titles: Lv.1 Wayfarer · Lv.5 Dusk Ranger · Lv.15 Starstrider · Lv.30 Dawn Warden'],
    details: ['详情 ›', 'Details ›'], assessmentButton: ['查看综合等级评分', 'View growth score'], growth: ['成长', 'Growth'], growthProgress: ['距下一级的成长进度', 'Progress toward next level'], points: ['{score} 分', '{score} pts'],
    scoreHint: ['综合评分 {score} / 1000；{next}；已采集 {coverage} / 5 项', 'Growth score {score} / 1000; {next}; {coverage} / 5 metrics available'], maxLevel: ['已达最高等级', 'Maximum level'], nextPoints: ['距下一级 {points} 分', '{points} points to next level'], scoreDetail: ['查看五项评分依据', 'See all five scoring factors'], incomplete: ['数据待补全', 'Incomplete data'],
    balanced: ['均衡成长', 'Balanced growth'], provisional: ['暂定评级', 'Provisional'], allMetrics: ['五项已采集', 'All metrics available'], lifetimeXp: ['累计行动 {xp} XP · 历史保留', '{xp} lifetime action XP · saved locally'],
    scoringRules: ['评分规则', 'Scoring rules'], rule1: ['五项各占 20%，各最高 200 分。每项按 200 × ln(1 + 数值) / ln(1 + 基准) 计算，四舍五入并封顶。每 20 分一级，最高 Lv.50。', 'Five equal factors, each capped at 200 points. Score = 200 × ln(1 + value) / ln(1 + benchmark), rounded and capped. Every 20 points grants a level, up to Lv.50.'],
    rule2: ['基准：累计行动 20,000 XP、粉丝 100,000、认证粉丝 25,000、日均曝光 100,000、日均互动 10,000。周期曝光和互动先折算日均。', 'Benchmarks: 20,000 action XP, 100,000 followers, 25,000 verified followers, 100,000 daily impressions and 10,000 daily engagements. Period totals are normalized per day.'],
    rule3: ['这是本插件的自定义评级。未知项不计分、不调整权重；综合等级会随账号数据变化，行动 XP 保留。', 'This is a custom extension score. Missing metrics earn no points and weights stay fixed. The rating can rise or fall with account data; action history stays saved.'],
    quests: ['每日委托', 'DAILY QUESTS'], dailySettings: ['每日任务', 'Daily quests'], posts: ['发帖', 'Posts'], replies: ['回复', 'Replies'], postsToday: ['今日发帖', 'Posts today'], repliesToday: ['今日回复', 'Replies today'], completed: ['今日委托已完成', 'Daily quests complete'], noGoal: ['未设目标', 'Goal disabled'], questHint: ['今日合计 {count} 条；自动识别记录 {auto} 条', '{count} recorded today; {auto} detected automatically'], disabledGoal: ['目标 0 表示不设此任务', 'A goal of 0 disables this quest'],
    followers: ['粉丝', 'Followers'], lastFollowers: ['粉丝 · 上次', 'Followers · last'], verifiedFollowers: ['认证粉丝', 'Verified fans'], impressions: ['曝光', 'Impressions'], engagements: ['互动', 'Engagements'], average: ['日均', 'daily avg'],
    followersHint: ['{date} 记录：{value} 粉丝', '{date} snapshot: {value} followers'], deltaHint: ['较 {date} 记录 {value}', '{value} since {date}'], profileHint: ['打开本人主页后读取粉丝数', 'Open your profile to read the follower count'], verifiedFansHint: ['{date} 记录：{value} 认证粉丝；对应 X 的 Checkmark followers', '{date}: {value} verified followers (X Checkmark followers)'], verifiedFansEmpty: ['打开分析页后读取 Checkmark followers', 'Open Analytics to read Checkmark followers'],
    periodHint: ['{period}：{value} 次 / 日；该范围合计 {total} 次', '{period}: {value} per day; {total} total for this period'], analyticsEmpty: ['打开分析页，明确统计周期后读取账号{metric}', 'Open Analytics with a clear period to read account {metric}'], tracked: ['已跟踪帖增览', 'Tracked view gain'], todayImpressions: ['今日曝光', 'Today impressions'], trackedHint: ['已跟踪帖子的今日新增浏览，不代表账号曝光，也不计入曝光评分', 'Observed view gains for tracked posts today; separate from account impressions and excluded from that score'], todayImpressionsHint: ['今天的账号曝光', 'Account impressions today'],
    statusButton: ['自动识别状态', 'Capture status'], status_connecting: ['正在连接', 'Connecting'], status_ready: ['自动识别已连接', 'Capture connected'], 'status_waiting-account': ['等待登录账号', 'Waiting for login'], 'status_account-mismatch': ['账号不一致', 'Account mismatch'], status_paused: ['自动识别已暂停', 'Capture paused'], status_error: ['需要刷新页面', 'Refresh needed'], status_demo: ['示例 · 未连接 X', 'Demo · offline'],
    conn_stopped: ['扩展已更新，请刷新 X 页面', 'Extension updated. Refresh this X page.'], conn_transport: ['无法连接本机记录，请刷新 X 页面', 'Local storage is unavailable. Refresh this X page.'], conn_config: ['正在连接本机记录', 'Connecting to local records.'], conn_paused: ['自动记录已暂停', 'Automatic capture is paused.'], conn_mismatch: ['当前为 @{active}，请切回 @{bound}', 'Signed in as @{active}. Switch back to @{bound}.'], conn_identity: ['等待识别登录账号，请在 X 完成登录', 'Sign in to X so your account can be detected.'], 'conn_handshake-timeout': ['自动记录未连接，请刷新 X 页面', 'Capture could not connect. Refresh this X page.'], conn_handshake: ['正在连接页面自动记录', 'Connecting to page capture.'], conn_ready: ['自动记录已连接，等待本页活动', 'Capture is connected and waiting for activity on this page.'], conn_demo: ['这里是界面演示，使用示例数据，未连接真实 X。', 'This preview uses sample data and is not connected to X.'],
    boundAccount: ['绑定账号', 'Account'], latestData: ['最近数据', 'Last response'], detectedToday: ['今日自动记录', 'Detected today'], ownBlue: ['自身蓝 V', 'Blue verification'], awaiting: ['等待识别', 'Waiting'], neverReceived: ['尚未收到数据', 'No response yet'], autoActions: ['{posts} 帖 · {replies} 回复', 'Posts: {posts} · replies: {replies}'], isVerified: ['已识别 · 蓝 V', 'Blue verified'], notVerified: ['当前未认证', 'Not verified'], unknownVerified: ['尚未识别', 'Not detected'],
    captureHelp: ['发帖 / 回复在成功响应后记录。页面数值在变化后重新读取；分析页会等待加载稳定。仅采集已打开页面的数据。', 'Posts and replies are recorded after a successful response. Page metrics refresh after changes; Analytics waits for a stable view. Only loaded page data can be captured.'], scan: ['立即检查本页', 'Check this page'], scanning: ['正在检查…', 'Checking…'], scanned: ['本页检查完成；未加载的数据无法读取', 'Page checked; unloaded data cannot be read'],
    postGoal: ['发帖目标', 'Post goal'], replyGoal: ['回复目标', 'Reply goal'], save: ['保存目标', 'Save goals'], correctPosts: ['修正今日发帖', 'Correct posts'], correctReplies: ['修正今日回复', 'Correct replies'], postsMinus: ['发帖减一', 'Subtract one post'], postsPlus: ['发帖加一', 'Add one post'], repliesMinus: ['回复减一', 'Subtract one reply'], repliesPlus: ['回复加一', 'Add one reply'], profileLink: ['本人主页 ↗', 'My profile ↗'], analyticsLink: ['分析页 ↗', 'Analytics ↗'], pause: ['暂停自动统计', 'Pause capture'], resume: ['恢复自动统计', 'Resume capture'], language: ['界面语言', 'Language'],
    settingsHelp: ['发帖 +20 XP · 回复 +5 XP，计入行动评分。数据保存在本机，关闭浏览器仍保留。北京时间 00:00 切换每日任务；手工修正不发布内容，也不触发每日宝箱。', 'Posts +20 XP · replies +5 XP, counted in the action score. Data stays on this device after closing the browser. Daily quests reset at midnight Beijing time. Manual corrections do not publish content or grant daily chests.'], saved: ['目标已保存', 'Goals saved'], languageSaved: ['语言已切换', 'Language updated'], failed: ['操作失败，请刷新 X 后重试', 'Unable to save. Refresh X and try again.'], levelUp: ['升至 LV. {level}', 'LEVEL {level}'],
    dim_action: ['行动', 'Actions'], dim_followers: ['总粉丝', 'Followers'], dim_verifiedFollowers: ['认证粉丝', 'Verified followers'], dim_impressions: ['曝光', 'Impressions'], dim_engagements: ['互动', 'Engagements'], unknown: ['未采集', 'Not collected'], unknownScore: ['等待数据 · 不计分', 'Awaiting data · not scored'], people: ['人', 'people'], perDay: ['次 / 日', '/ day'], actionSource: ['本机累计 · 发帖 20 XP / 回复 5 XP', 'Local lifetime · posts 20 XP / replies 5 XP'], snapshot: ['{date} 快照', '{date} snapshot'], sampledDays: ['已采集 {days} 天日均', 'Average of {days} collected days'], periodDays: ['{label} · {days} 天日均', '{label} · {days}-day average'], today: ['今天', 'Today'], benchmark: ['满分基准：{value} {unit}', 'Full-score benchmark: {value} {unit}'],
    collection: ['收藏阁', 'RELIQUARY'], collectionButton: ['打开宝物收藏', 'Open relic collection'], collectionCount: ['已发现 {owned} / {total}', '{owned} / {total} found'], pending: ['{count} 个待开', '{count} ready'], noChest: ['下一段旅程的奖励', 'Rewards for the journey'], chestReady: ['旅途馈赠', 'A gift from the road'], chestIdle: ['等待下一份宝藏', 'Your next treasure awaits'], openChest: ['开启宝箱', 'Open chest'], opening: ['正在开启…', 'Opening…'], nextReward: ['下个等级宝箱 · Lv.{level}', 'Next level chest · Lv.{level}'], allLevels: ['等级旅程已圆满', 'Level milestones complete'], lootRules: ['完成每日自动统计目标得 1 箱；等级每跨 5 级得 1 箱。随机获得 1 件藏品，集齐前不重复。仅作收藏，不改变账号评分。', 'Earn one chest for completing daily auto-tracked goals and one at each 5-level milestone. Each chest reveals one random relic, without duplicates until the set is complete. Relics do not change your score.'], discovered: ['新发现', 'DISCOVERED'], owned: ['已收藏', 'Collected'], locked: ['尚未发现', 'Undiscovered'], itemHint: ['继续完成旅程，发现这件藏品。', 'Keep completing your journey to discover this relic.'], common: ['精良', 'Fine'], rare: ['稀有', 'Rare'], epic: ['史诗', 'Epic'], noItems: ['你的收藏从第一只宝箱开始。', 'Your collection begins with the first chest.'], copied: ['收藏 ×{count}', 'Collected ×{count}']
  };
  function t(language, key, params = {}) {
    const message = messages[key]?.[language === 'en' ? 1 : 0] || key;
    return message.replace(/\{(\w+)\}/g, (_, name) => String(params[name] ?? ''));
  }
  globalThis.XFocusI18n = { t };
})();
