(() => {
  const messages = {
    title: ['冒险档案', 'ADVENTURER'], hud: ['X Focus 每日任务', 'X Focus daily quests'], settings: ['任务设置', 'Quest settings'], collapse: ['仅显示发帖和回复', 'Show posts and replies only'], expand: ['展开 X Focus 每日任务', 'Expand X Focus daily quests'],
    dragHint: ['拖动移动；方向键微调位置', 'Drag to move; use arrow keys to fine-tune the position'], miniMode: ['仅显示发帖和回复', 'Show posts and replies only'], fullMode: ['展开完整档案', 'Expand full character sheet'], panelPosition: ['面板位置', 'Panel position'], dockLeft: ['贴左边', 'Dock left'], dockRight: ['贴右边', 'Dock right'], autoPosition: ['自动位置', 'Automatic'], positionSaved: ['位置已保存', 'Position saved'], layoutHelp: ['拖动顶部移动面板；靠近左右边缘时自动停靠。位置和显示模式保存在本机。', 'Drag the header to move the panel. It docks near the left or right edge. Position and display mode are saved on this device.'],
    adventurer: ['冒险者', 'Adventurer'], identityHint: ['登录 X 后自动识别账号', 'Your account is detected after signing in to X'], verified: ['X 蓝 V 已认证', 'X blue verified'], readAt: ['{date} 读取', 'Read {date}'],
    rank0: ['启程旅人', 'Wayfarer'], rank1: ['暮光游侠', 'Dusk Ranger'], rank2: ['星辉行者', 'Starstrider'], rank3: ['黎明守望', 'Dawn Warden'],
    rankHint: ['等级称号：Lv.1 启程旅人 · Lv.5 暮光游侠 · Lv.15 星辉行者 · Lv.30 黎明守望', 'Titles: Lv.1 Wayfarer · Lv.5 Dusk Ranger · Lv.15 Starstrider · Lv.30 Dawn Warden'],
    details: ['详情 ›', 'Details ›'], assessmentButton: ['查看行动经验明细', 'View action experience'], growth: ['经验', 'EXP'], growthProgress: ['距下一级的经验进度', 'Experience toward next level'],
    experienceHint: ['累计 {total} EXP；距下一级 {remaining} EXP。发帖 +5 EXP，回复 +1 EXP。', '{total} total EXP; {remaining} EXP to next level. Posts +5 EXP, replies +1 EXP.'], nextPoints: ['距下一级 {points} EXP', '{points} EXP to next level'], scoreDetail: ['查看累计发帖与回复经验', 'See lifetime post and reply experience'],
    actionGrowth: ['行动经验', 'Action experience'], lifetimeXp: ['累计 {xp} EXP · 本机记录保留', '{xp} lifetime EXP · saved locally'], lifetime_posts: ['累计发帖', 'Lifetime posts'], lifetime_replies: ['累计回复', 'Lifetime replies'], actionCalculation: ['{count} 条 × {rate} EXP', '{count} × {rate} EXP'],
    scoringRules: ['升级规则', 'Level rules'], rule1: ['启用插件后，每发帖 +5 EXP，每回复 +1 EXP。初始为 Lv.1 / 0 EXP；每累计 100 EXP 升一级，不设等级上限。', 'After enabling the extension, each post earns 5 EXP and each reply earns 1 EXP. Start at Lv.1 / 0 EXP and gain a level every 100 EXP, with no level cap.'],
    rule2: ['粉丝、认证粉丝、曝光和互动仅作观察，不计入经验；切换 Analytics 统计周期不会改变等级。', 'Followers, verified followers, impressions and engagements are for observation only. Switching the Analytics period never changes your level.'],
    rule3: ['已有本地发帖与回复记录按 5 / 1 EXP 重新计算，历史不清空。手工修正会调整对应经验，修改每日目标不会增加经验。', 'Existing local posts and replies are recalculated at 5 / 1 EXP; history is kept. Count corrections adjust experience, while changing daily goals adds no experience.'],
    quests: ['每日委托', 'DAILY QUESTS'], dailySettings: ['每日任务', 'Daily quests'], posts: ['发帖', 'Posts'], replies: ['回复', 'Replies'], postsToday: ['今日发帖', 'Posts today'], repliesToday: ['今日回复', 'Replies today'], completed: ['今日委托已完成', 'Daily quests complete'], noGoal: ['未设目标', 'Goal disabled'], questHint: ['今日合计 {count} 条；自动识别记录 {auto} 条', '{count} recorded today; {auto} detected automatically'], disabledGoal: ['目标 0 表示不设此任务', 'A goal of 0 disables this quest'],
    followers: ['粉丝', 'Followers'], lastFollowers: ['粉丝 · 上次', 'Followers · last'], verifiedFollowers: ['认证粉丝', 'Verified fans'], impressions: ['曝光', 'Impressions'], engagements: ['互动', 'Engagements'], average: ['日均', 'daily avg'],
    followersHint: ['{date} 记录：{value} 粉丝', '{date} snapshot: {value} followers'], deltaHint: ['较 {date} 记录 {value}', '{value} since {date}'], profileHint: ['打开本人主页后读取粉丝数', 'Open your profile to read the follower count'], verifiedFansHint: ['{date} 记录：{value} 认证粉丝；对应 X 的 Checkmark followers', '{date}: {value} verified followers (X Checkmark followers)'], verifiedFansEmpty: ['打开分析页后读取 Checkmark followers', 'Open Analytics to read Checkmark followers'],
    periodHint: ['{period}：{value} 次 / 日；该范围合计 {total} 次；不影响等级', '{period}: {value} per day; {total} total for this period; does not affect level'], analyticsEmpty: ['打开分析页，明确统计周期后读取账号{metric}', 'Open Analytics with a clear period to read account {metric}'], tracked: ['已跟踪帖增览', 'Tracked view gain'], todayImpressions: ['今日曝光', 'Today impressions'], trackedHint: ['已跟踪帖子的今日新增浏览，不代表账号曝光，不增加经验', 'Observed view gains for tracked posts today; separate from account impressions and do not add EXP'], todayImpressionsHint: ['今天的账号曝光，不影响等级', 'Account impressions today; does not affect level'],
    statusButton: ['自动识别状态', 'Capture status'], status_connecting: ['正在连接', 'Connecting'], status_ready: ['自动识别已连接', 'Capture connected'], 'status_waiting-account': ['等待登录账号', 'Waiting for login'], 'status_account-mismatch': ['账号不一致', 'Account mismatch'], status_paused: ['自动识别已暂停', 'Capture paused'], status_error: ['需要刷新页面', 'Refresh needed'], status_demo: ['示例 · 未连接 X', 'Demo · offline'],
    conn_stopped: ['扩展已更新，请刷新 X 页面', 'Extension updated. Refresh this X page.'], conn_transport: ['无法连接本机记录，请刷新 X 页面', 'Local storage is unavailable. Refresh this X page.'], conn_config: ['正在连接本机记录', 'Connecting to local records.'], conn_paused: ['自动记录已暂停', 'Automatic capture is paused.'], conn_mismatch: ['当前为 @{active}，请切回 @{bound}', 'Signed in as @{active}. Switch back to @{bound}.'], conn_identity: ['等待识别登录账号，请在 X 完成登录', 'Sign in to X so your account can be detected.'], 'conn_handshake-timeout': ['自动记录未连接，请刷新 X 页面', 'Capture could not connect. Refresh this X page.'], conn_handshake: ['正在连接页面自动记录', 'Connecting to page capture.'], conn_ready: ['自动记录已连接，等待本页活动', 'Capture is connected and waiting for activity on this page.'], conn_demo: ['这里是界面演示，使用示例数据，未连接真实 X。', 'This preview uses sample data and is not connected to X.'],
    status_degraded: ['实时监听待恢复', 'Live capture interrupted'], 'conn_observer-detached': ['实时监听可能被页面替换，可检查本页补采；刷新 X 后重试。', 'The page may have replaced live capture. Check this page for recovery, or refresh X.'],
    boundAccount: ['绑定账号', 'Account'], latestData: ['最近记账', 'Last action saved'], detectedToday: ['今日自动记录', 'Detected today'], ownBlue: ['自身蓝 V', 'Blue verification'], awaiting: ['等待识别', 'Waiting'], neverReceived: ['尚未记录发帖或回复', 'No actions saved yet'], autoActions: ['{posts} 帖 · {replies} 回复', 'Posts: {posts} · replies: {replies}'], isVerified: ['已识别 · 蓝 V', 'Blue verified'], notVerified: ['当前未认证', 'Not verified'], unknownVerified: ['尚未识别', 'Not detected'],
    captureHelp: ['“已连接”仅代表监听已接通，不代表已记账。漏记时打开本人主页，让近期帖子加载；可核对“最近记账”和今日自动记录。相同帖子只计一次，不确定类型的页面内容不会猜作发帖。', 'Connected means the listener is active, not that an action was saved. Open your profile to load recent posts for recovery. Check the last saved action and daily counts. Each post counts once; ambiguous page content is not guessed as an original post.'], scan: ['立即检查本页', 'Check this page'], scanning: ['正在检查…', 'Checking…'], scanned: ['本页检查完成；未加载的数据无法读取', 'Page checked; unloaded data cannot be read'],
    postGoal: ['发帖目标', 'Post goal'], replyGoal: ['回复目标', 'Reply goal'], save: ['保存目标', 'Save goals'], correctPosts: ['修正今日发帖', 'Correct posts'], correctReplies: ['修正今日回复', 'Correct replies'], postsMinus: ['发帖减一', 'Subtract one post'], postsPlus: ['发帖加一', 'Add one post'], repliesMinus: ['回复减一', 'Subtract one reply'], repliesPlus: ['回复加一', 'Add one reply'], profileLink: ['本人主页 ↗', 'My profile ↗'], analyticsLink: ['分析页 ↗', 'Analytics ↗'], pause: ['暂停自动统计', 'Pause capture'], resume: ['恢复自动统计', 'Resume capture'], language: ['界面语言', 'Language'],
    settingsHelp: ['发帖 +5 EXP · 回复 +1 EXP，每 100 EXP 升一级。数据保存在本机，关闭浏览器仍保留。北京时间 00:00 切换每日任务；手工修正不发布内容，也不触发每日宝箱。', 'Posts +5 EXP · replies +1 EXP. Every 100 EXP grants a level. Data stays on this device after closing the browser. Daily quests reset at midnight Beijing time. Manual corrections do not publish content or grant daily chests.'], saved: ['目标已保存', 'Goals saved'], languageSaved: ['语言已切换', 'Language updated'], failed: ['操作失败，请刷新 X 后重试', 'Unable to save. Refresh X and try again.'], levelUp: ['升至 LV. {level}', 'LEVEL {level}'],
    unknown: ['未采集', 'Not collected'], snapshot: ['{date} 快照', '{date} snapshot'], sampledDays: ['已采集 {days} 天日均', 'Average of {days} collected days'], periodDays: ['{label} · {days} 天日均', '{label} · {days}-day average'], today: ['今天', 'Today'],
    collection: ['收藏阁', 'RELIQUARY'], collectionButton: ['打开宝物收藏', 'Open relic collection'], collectionCount: ['已发现 {owned} / {total}', '{owned} / {total} found'], pending: ['{count} 个待开', '{count} ready'], noChest: ['下一段旅程的奖励', 'Rewards for the journey'], chestReady: ['旅途馈赠', 'A gift from the road'], chestIdle: ['等待下一份宝藏', 'Your next treasure awaits'], openChest: ['开启宝箱', 'Open chest'], opening: ['正在开启…', 'Opening…'], nextReward: ['下个等级宝箱 · Lv.{level}', 'Next level chest · Lv.{level}'], allLevels: ['等待下个等级里程碑', 'Waiting for the next milestone'], lootRules: ['完成每日自动统计目标得 1 箱；等级每跨 5 级得 1 箱。随机获得 1 件藏品，集齐前不重复。仅作收藏，不增加 EXP 或改变等级。', 'Earn one chest for completing daily auto-tracked goals and one at each 5-level milestone. Each chest reveals one random relic, without duplicates until the set is complete. Relics do not add EXP or change your level.'], discovered: ['新发现', 'DISCOVERED'], owned: ['已收藏', 'Collected'], locked: ['尚未发现', 'Undiscovered'], itemHint: ['继续完成旅程，发现这件藏品。', 'Keep completing your journey to discover this relic.'], common: ['精良', 'Fine'], rare: ['稀有', 'Rare'], epic: ['史诗', 'Epic'], noItems: ['你的收藏从第一只宝箱开始。', 'Your collection begins with the first chest.'], copied: ['收藏 ×{count}', 'Collected ×{count}']
  };
  function t(language, key, params = {}) {
    const message = messages[key]?.[language === 'en' ? 1 : 0] || key;
    return message.replace(/\{(\w+)\}/g, (_, name) => String(params[name] ?? ''));
  }
  globalThis.XFocusI18n = { t };
})();
